#!/usr/bin/bash
# Arnav Mathur
# CSE 374 22sp HW 2
# Part 4
# 4/12/2022

# Prints error if less than two arguments are provided.
if [ $# -lt 2 ]; then
    echo "Error 404: this function requires two or more arguments to be passed" >&2
    exit 1
fi 

# Adds date and number of lines of all files to first file.
OUTPUT="$1"
TOTAL_LINES=0

shift

date >> "$OUTPUT"

# Outputs the basename of every file alongside the number of lines in the current file.
# For every file given checks the line count and adds it to parameter TOTAL_LINES.
for i in "$@"; do
    x=`wc -l < "$i"`
    echo "$x $(basename $i)">>"$OUTPUT"
    let TOTAL_LINES=TOTAL_LINES+x
done

echo "$TOTAL_LINES total">>"$OUTPUT"
exit 0

